version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - ./app.env
    ports:
      - '5438:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: